language: node_js

compiler: gcc
sudo: false
os: linux

node_js:
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - echo $TRAVIS_NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.9";
      export CXX="g++-4.9";
      export LINK="gcc-4.9";
      export LINKXX="g++-4.9";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
